sudo: required
services: docker

env:
  global:
  # Docker Username
  - secure: "A2Ob0PDCm41JLCXR6VD3mqSJATIJTqnBiaBJwK3uSY9V992SDwJmTvzYbzSoYfoB0G3OFPVzKwiWBQXzfuzsx875vWRJAQ+wqtaunZVuPtjE+Juiq74VkAlIlAXUWASlxFgBRA9nK/748XvjdCrIlRXpX845+aLBnXzfiCAsr+Z29ZYWaEkcR+YJ3uGfXNoPNuLcIcZudBmf0ffNYpdAo/ez/TEwOS14F4MtS0qgzFKrOZIXp1st+hWG43FWDiq1z048ZXbti+rK/AlaCPbAcKraQZkFXGCZmif09su5iY8c9CeuFltENjggORilGmR7KYE8ZWiksUViUDU6sr9uFfix1EXU9H8YZszcYvnFgjy665yOAmeIrbWRIUIouXJjva1uqxtYduXPkFnIO+/gfp7Ug2P3rvReZj5PiRuRuiPk+Kh3Gl/uunLrcfTc4hQnnYOPBFJ4ghtSyW4rCn23pIFgnGdrQgnPX2INlU/NHnaWpPz7J/ybia7xr17+PE6Z474i9/4lrjGwQQVQWvwlwGyqnLqFXgCF2v3EDWws2SOce4RlGNA3q3cJMPRj55oewAQRA1XbwnIPoz7MVFI0wML2enAvv8h6k20/JGzt1VUHABnQpgwSo+eIYkdKtPLx7LtmXBx3ZYf/mcEEpfKISgXfCBuhXfFf2CExXzpZCyk="
  # Docker Password
  - secure: "lF1Jn2Zd9ZoFEZqvV00ZgE26CXHOt4mQofVJqPiqLSnKAEe2h3c87QPyrgTIigqC8GpgcsYmYnpQRRXxdUK5NKgddXHFpdVL6GlUUKCuK8i7MHgmRG7sMSpda8dPDOMWClJnxyzUofvyog2rfHiw7nEF2Un2SfC6bft6cwuiuqsUfW7+iCsT478wkkSD2lYMji4MxgakD2UCESVFnGC5O44h+NFntBOBNHg82McLmsRM6YPrlmDL2vSISqdsTLIftX984L/o/CTbyNjHahxeMxjufbOlXZC3wPXQuEzSxOHZiNo/mplFwkvd11n5qxdT4vkVYdQpDJpg5Gk9XCD5OVpaV5cSL8Cd9TDGD87ancmayXx9wDQ0MDjZkii+HhcjVvUrUw5cG1aNKUHhBEZro5VstvT9tWEmz9C2D4WwUOuX5E6q48xvYEdUyPrsCA6J+Z2YEV0xmtN+RbwQPxoq1u1RKHXvn4neWB3g+TayqQO/ZQTdCl0dGDA6OLr4s/vKwTaMr/KFnk8/NSh54JiYNsa7bB2s/j4aEYAkGXKKVxu2ColNfHyOZs5KJydTcwRGWUUnSUI32lb2KF7HsHiIQupkNUg3Y6F2RRcWPIyoi5zDZ7V5nMeXiel6j1XUFsIz1EzBMHleQ4uaz15bmf8Q+BTjGS8HYw7sFw7DgFR61M0="
  # Docker Hub Token
  - secure: "dlfMtawhJAv2KKz57b22ct4pytuZK3W0BQbekEOpzdR387Qrce2Pi/iKGXzUjBqkrOUyhy5nm5WxUoJ+4K5LsXL/htCnKOPN1hdPZBHH/8UsipmYbX29OX+aF0fQssndm+V3bAyzXk1o79gUNxkOq6ZwHgTCwi8qib/o0F1Dk/1ZiH9HHairqUMO8Pxlm+SPQTZEClQqvFlP9aWQ34i+4U4vV+SbcA1BUfdsn44D9kQS/lQm7cIFa1k/jjDGDn+tcI+aKRSsQ2C3uNaSSaYspgxBPDHbPbj5W0H1hN4SdDJYNRoE7mNORAey5JVvLClG782oc3YzEwD7QjnKhBob26ICI1qmS6Uxx5v044hdkQyJIqDj7BxHfxUT1xXrdKtYt7UEzJAo/q76VAJNzTfgg47EdnYS5RBWmmnltZ17f2LDfYoMaxrQXlhglL6BNcHP4pE+1XkXDc69G9oTTuP9X+bGVKcVlm13dbUAjgeJ7B0XZsc/27wkKQQl8j0bICA1KiaDOBybfdy1urn7/C54nlADcNqSctWiiz1en+jzuslGYhvBUGdoIVtDjwfC23OpNp7Juqw3o4RjGoXi27jG78DnDCpNSZMS07Yihl7yqdNb1fl11e8WV/kirGy8kTZOvXuU9k4UBztMJ/Q2Dj/wiCPosYdns/oefTySA4+5TqY="
  matrix:
  - VERSION=1.0-alpine
  - VERSION=1.1-alpine
  # legacy
  - VERSION=1.0.0-alpine
  - VERSION=1.0.1-alpine

before_install:
#- make install

script:
- travis_retry make build v=${VERSION} dev=dev
- make tags

after_script:
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
# check if branch=master and the current build is no pull request, then push it to docker hub
#- [[ "$TRAVIS_BRANCH" == "master" ]] && [[ "$TRAVIS_PULL_REQUEST" == "false" ]] && make push;
- if [[ "$TRAVIS_BRANCH" == "master" ]]; then 
    if [[ "$TRAVIS_PULL_REQUEST" == "false" ]]; then 
      make push;
    fi; 
  fi

after_success:
# notify Docker Hub to make a new build
#- [[ "$TRAVIS_BRANCH" == "master" ]] && [[ "$TRAVIS_PULL_REQUEST" == "false" ]] && make notify-hub-docker-com TOKEN=$DOCKER_HUB_TOKEN
- if [[ "$TRAVIS_BRANCH" == "master" ]]; then 
    if [[ "$TRAVIS_PULL_REQUEST" == "false" ]]; then 
      make notify-hub-docker-com TOKEN=$DOCKER_HUB_TOKEN
    fi; 
  fi

# don't notify me when things fail
notifications:
  email: false